[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "GDyMc5kxzHhREL5jcLTGEnR1Xc3tL8aifJqnLQ7fJkd2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/darius/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
